version: "2"
services:
  api:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - ./api:/app
  db:
    container_name: social-db
    image: mongo
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "27017:27017"
